### ISSUE TITLE
HW2ISSUE#10:  Incorrect styles using

### ISSUE THREAD

**Issue by DennyTim** [RohitSavalagi/Ramda#10]
https://github.com/RohitSavalagi/Ramda/blob/0a6379b97a5e71937ac9673870ca7d5a9bc38a23/index.html#L38

Better to use the following layout for the sidebar:

```html
        <aside class="sidebar">
            <a href="#" class="sidebar __item">Ramda</a>
            <a href="#" class="sidebar __item">Why Ramda?</a>
            <a href="#" class="sidebar __item">What's Different?</a>
            <a href="#" class="sidebar __item">Introduction</a>
            <a href="#" class="sidebar __item">Philosophy</a>
        </aside>
```
```css
.sidebar {
    width: 344px;
    margin-top: 51px;
    border: 1px solid black;
    align-self: start;
}

.sidebar __item:hover {
    padding-left: 70px;
    transition: All 0.4s ease;
    color: black;
    background: rgb(220, 220, 220);
}

.sidebar __item {
    display: block;
    padding-left: 44px;
    font-size: 27px;
    padding-top: 20px;
    padding-bottom: 20px;
    text-decoration: none;
    color: rgb(70, 87, 99);
}
```
