### ISSUE TITLE
HW2ISSUE#9: Width restrictions

### ISSUE THREAD

**Issue by DennyTim** [RohitSavalagi/Ramda#9]
https://github.com/RohitSavalagi/Ramda/blob/0a6379b97a5e71937ac9673870ca7d5a9bc38a23/index.html#L19

If you wanna use width restrictions for the page, you need to use the following structure:

```html
<header class="...">
   <div class="container">...</div>
</header>
<main class="...">
   <div class="container">...</div>
</main >
<footer class="...">
   <div class="container">...</div>
</footer>
```

```css
.container {
    width: 960px;
    margin: 0 auto;
    text-align: center; /* can be used optionally if you wanna align the whole section */
}
```
